steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '--build-arg'
  - 'version=$SHORT_SHA'
  - '-t'
  - 'europe-west2-docker.pkg.dev/fleet-coyote-341511/nap-theme/prototype:$SHORT_SHA'
  - '.'
  - '--progress=plain'
  - '--no-cache'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'europe-west2-docker.pkg.dev/fleet-coyote-341511/nap-theme/prototype:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/git'
  id: Update Hash 
  volumes:
  - name: 'manifestsvolume'
    path: '/data'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" manifests/deployment.yaml.tpl > manifests/deployment.yaml
    sed -i "s#_DOMAINNAME#${_DOMAINNAME}#g" manifests/certificate.yaml
    cp manifests/certificate.yaml /data/certificate.yaml
    cp manifests/ingress.yaml /data/ingress.yaml
    cp manifests/service.yaml /data/service.yaml
    cp manifests/deployment.yaml /data/deployment.yaml

- name: "gcr.io/cloud-builders/gke-deploy"
  volumes:
    - name: 'manifestsvolume'
      path: '/data'
  args:
  - run
  - --filename=/data/
  - --location=europe-west2
  - --namespace=${_NAMESPACE}
  - --cluster=${_CLUSTER}
  timeout: 600s

substitutions:
    _NAMESPACE: kits-dft-test
    _CLUSTER: kits-dft-test-cluster
