steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '--build-arg'
  - 'version=$SHORT_SHA'
  - '-t'
  - 'europe-west2-docker.pkg.dev/fleet-coyote-341511/nap-theme/prototype:$SHORT_SHA'
  - '.'
  - '--progress=plain'
  - '--no-cache'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'europe-west2-docker.pkg.dev/fleet-coyote-341511/nap-theme/prototype:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/git'
  id: Update Hash 
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" manifest/deployment.yaml.tpl manifests/deployment.yaml
