steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '--build-arg'
  - 'version=$SHORT_SHA'
  - '-t'
  - 'europe-west2-docker.pkg.dev/fleet-coyote-341511/nap-theme/prototype:$SHORT_SHA'
  - '.'
  - '--progress=plain'
  - '--no-cache'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'europe-west2-docker.pkg.dev/fleet-coyote-341511/nap-theme/prototype:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/git'
  id: Update Hash 
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git config --global user.name "cloudbuilder"
    git config --global user.email "cloudbuilder@gmail.com"
    git push origin --delete candidate
    git checkout -b candidate
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" manifests/deployment.yaml.tpl manifests/deployment.yaml
    git add manifests/deployment.yaml
    git commit -m "europe-docker.pkg.dev/prototype:${SHORT_SHA} Built from commit ${COMMIT_SHA} of repository prototype Author: $(git log --format='%an <%ae>' -n 1 HEAD)"
    git push --set-upstream origin candidate

